# docker file
FROM python:3.10-slim

# set the working directory in the container
WORKDIR /app

# copy the dependencies file to the working directory
COPY ./requirement.txt /app/requirement.txt

# install dependencies
RUN pip install -r requirement.txt --progress-bar off --default-timeout=100

COPY . .

# command to run on container start uvicorn controller_web_socket_redis:app --host 0.0.0.0 --port 8004  --workers 64
CMD ["uvicorn", "controller_web_socket_redis:app", "--workers", "64", "--host", "0.0.0.0", "--port", "8004", "--loop", "uvloop", "--http", "h11"]